# Generated by Django 4.2.2 on 2024-02-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLogModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('steps', models.IntegerField()),
                ('pushups', models.IntegerField()),
                ('situps', models.IntegerField()),
                ('squarts', models.IntegerField()),
                ('lunges', models.IntegerField()),
            ],
            options={
                'db_table': 'exerciseLog',
            },
        ),
    ]
