# Generated by Django 4.2.2 on 2024-02-14 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciselogmodel',
            old_name='id',
            new_name='index',
        ),
    ]
