# Generated by Django 4.2.2 on 2024-02-14 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_rename_id_exerciselogmodel_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselogmodel',
            name='date',
        ),
    ]
