# Generated by Django 4.2.2 on 2024-02-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_remove_exerciselogmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselogmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Time'),
        ),
    ]
