# Generated by Django 4.2.10 on 2024-03-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(default='profile_pic_default.png', upload_to='profile_pic')),
            ],
        ),
    ]
